const UserData = {
  1: {
    details: {
      name: "Test account1",
      email: "buddy@email.com",
      password: "password",
      isAdmin: false,
    },
    count: 3,
    designDetails: {
      ids: [
        {
          id: 1,
          Username: "111",
          Usertitle: "Your title from usedata api",
          phone: "1",
          web: "1",
          mail: "hello@gamil.com",
          locations: "cbe",
          links: {
            insta: "https://www.github.com/buddy",
            facebook: "https://www.github.com/buddy",
            X: "https://www.github.com/buddy",
            youtube: "https://www.github.com/buddy",
            linkedin: "https://www.github.com/buddy",
          },
        },
        {
          id: 2,
          Username: "222",
          Usertitle: "title2",
          phone: "2",
          web: "2",
          mail: "hello@gamil.com",
          locations: "cbe",
          links: {
            insta: "https://www.github.com/buddy",
            facebook: "https://www.github.com/buddy",
            X: "https://www.github.com/buddy",
            youtube: "https://www.github.com/buddy",
            linkedin: "https://www.github.com/buddy",
          },
        },
        {
          id: 3,
          Username: "33",
          Usertitle: "Your title from usedata api",
          phone: "3",
          web: "3",
          mail: "hello@gamil.com",
          locations: "cbe",
        },
      ],
      names: "buddy",
      title: "Your title from usedata api",
      links: {
        insta: "https://www.github.com/buddy",
        facebook: "https://www.github.com/buddy",
        X: "https://www.github.com/buddy",
        youtube: "https://www.github.com/buddy",
        linkedin: "https://www.github.com/buddy",
      },
      contactDetails: {
        phone: "231231342",
        web: "www.buddyblog.site",
        mail: "hello@gamil.com",
        locations: "cbe",
      },
    },
  },
  2: {
    details: { name: "buddy", email: "11", password: "11", isAdmin: false },
    count: 3,
    designDetails: {
      ids: [
        {
          id: 1,
          Username: "111",
          Usertitle: "Your title from usedata api",
          phone: "1",
          web: "1",
          mail: "hello@gamil.com",
          locations: "cbe",
          links: {
            insta: "https://www.github.com/buddy",
            facebook: "https://www.github.com/buddy",
            X: "https://www.github.com/buddy",
            youtube: "https://www.github.com/buddy",
            linkedin: "https://www.github.com/buddy",
          },
        },
        {
          id: 2,
          Username: "222",
          Usertitle: "title2",
          phone: "2",
          web: "2",
          mail: "hello@gamil.com",
          locations: "cbe",
          links: {
            insta: "https://www.github.com/buddy",
            facebook: "https://www.github.com/buddy",
            X: "https://www.github.com/buddy",
            youtube: "https://www.github.com/buddy",
            linkedin: "https://www.github.com/buddy",
          },
        },
        {
          id: 3,
          Username: "33",
          Usertitle: "Your title from usedata api",
          phone: "3",
          web: "3",
          mail: "hello@gamil.com",
          locations: "cbe",
        },
      ],
      names: "buddy",
      title: "Your title from usedata api",
      links: {
        insta: "https://www.github.com/buddy",
        facebook: "https://www.github.com/buddy",
        X: "https://www.github.com/buddy",
        youtube: "https://www.github.com/buddy",
        linkedin: "https://www.github.com/buddy",
      },
      contactDetails: {
        phone: "231231342",
        web: "www.buddyblog.site",
        mail: "hello@gamil.com",
        locations: "cbe",
      },
    },
  },
  3: {
    details: {
      name: "Dinesh",
      email: "admin",
      password: "11",
      isAdmin: true,
    },
    count: 3,
    designDetails: {
      ids: [
        {
          id: 1,
          Username: "111",
          Usertitle: "Your title from usedata api",
          phone: "1",
          web: "1",
          mail: "hello@gamil.com",
          locations: "cbe",
          links: {
            insta: "https://www.github.com/buddy",
            facebook: "https://www.github.com/buddy",
            X: "https://www.github.com/buddy",
            youtube: "https://www.github.com/buddy",
            linkedin: "https://www.github.com/buddy",
          },
        },
        {
          id: 2,
          Username: "222",
          Usertitle: "title2",
          phone: "2",
          web: "2",
          mail: "hello@gamil.com",
          locations: "cbe",
          links: {
            insta: "https://www.github.com/buddy",
            facebook: "https://www.github.com/buddy",
            X: "https://www.github.com/buddy",
            youtube: "https://www.github.com/buddy",
            linkedin: "https://www.github.com/buddy",
          },
        },
        {
          id: 3,
          Username: "33",
          Usertitle: "Your title from usedata api",
          phone: "3",
          web: "3",
          mail: "hello@gamil.com",
          locations: "cbe",
        },
      ],
      names: "buddy",
      title: "Your title from usedata api",
      links: {
        insta: "https://www.github.com/buddy",
        facebook: "https://www.github.com/buddy",
        X: "https://www.github.com/buddy",
        youtube: "https://www.github.com/buddy",
        linkedin: "https://www.github.com/buddy",
      },
      contactDetails: {
        phone: "231231342",
        web: "www.buddyblog.site",
        mail: "hello@gamil.com",
        locations: "cbe",
      },
    },
  },
  4: {
    details: {
      name: "Dinesh",
      email: "admin",
      password: "11",
      isAdmin: true,
    },
    count: 3,
    designDetails: {
      ids: [
        {
          id: 1,
          Username: "111",
          Usertitle: "Your title from usedata api",
          phone: "1",
          web: "1",
          mail: "hello@gamil.com",
          locations: "cbe",
          links: {
            insta: "https://www.github.com/buddy",
            facebook: "https://www.github.com/buddy",
            X: "https://www.github.com/buddy",
            youtube: "https://www.github.com/buddy",
            linkedin: "https://www.github.com/buddy",
          },
        },
        {
          id: 2,
          Username: "222",
          Usertitle: "title2",
          phone: "2",
          web: "2",
          mail: "hello@gamil.com",
          locations: "cbe",
          links: {
            insta: "https://www.github.com/buddy",
            facebook: "https://www.github.com/buddy",
            X: "https://www.github.com/buddy",
            youtube: "https://www.github.com/buddy",
            linkedin: "https://www.github.com/buddy",
          },
        },
        {
          id: 3,
          Username: "33",
          Usertitle: "Your title from usedata api",
          phone: "3",
          web: "3",
          mail: "hello@gamil.com",
          locations: "cbe",
        },
      ],
      names: "buddy",
      title: "Your title from usedata api",
      links: {
        insta: "https://www.github.com/buddy",
        facebook: "https://www.github.com/buddy",
        X: "https://www.github.com/buddy",
        youtube: "https://www.github.com/buddy",
        linkedin: "https://www.github.com/buddy",
      },
      contactDetails: {
        phone: "231231342",
        web: "www.buddyblog.site",
        mail: "hello@gamil.com",
        locations: "cbe",
      },
    },
  },
};

export default UserData;
